version: '3.4'

services:
  productservice:
    build:
      context: ./ProductService
    ports:
      - "5001:80"
    networks:
      - microservices-network

  orderservice:
    build:
      context: ./OrderService
    ports:
      - "5002:80"
    networks:
      - microservices-network

  customerservice:
    build:
      context: ./CustomerService
    ports:
      - "5003:80"
    networks:
      - microservices-network

networks:
  microservices-network:
    driver: bridge
